### ISSUE TITLE
Implement an API and give me the ability to deploy with docker.

### ISSUE THREAD

**Issue by ianpurton** [laiyer-ai/llm-guard#17]
When implementing an LLM pipeline I'm generally deploying to kubernetes.

Other parts of our pipeline are already containerized, for example [unstructured ](https://unstructured.io/) has an API and they build a docker container.

So it would be nice if llm-guard also had a Docker file and an API that we can integrate with.

**Comment by asofter** [comment]
Hey @ianpurton , thanks for contacting us and sharing the idea! It's in development actually and should be deployed this week. It will be a dockerized API using fastapi. I will update you once it's done.

**Comment by asofter** [comment]
Hey @ianpurton , there is an update. API version is Live and there is Docker image available: https://llm-guard.com/usage/api/

Thanks for raising this :)
