### ISSUE TITLE
Dataset for training prompt injection v2 model

### ISSUE THREAD

**Issue by priya-dwivedi** [laiyer-ai/llm-guard#33]
Hello, Can you share the dataset on which you trained the prompt injection v2 model?
https://huggingface.co/hubert233/GPTFuzz

Will be great if u can add this info into the model card.

**Comment by asofter** [comment]
Hey @priya-dwivedi , thanks for reaching out. This dataset was generated for evaluation of [this paper](https://arxiv.org/pdf/2309.10253.pdf) - repository https://github.com/sherdencooper/GPTFuzz#models
