### ISSUE TITLE
Circular import caused by filename of example script openai.py

### ISSUE THREAD

**Issue by tcpiplab** [laiyer-ai/llm-guard#34]
**Describe the bug**
The Python interpreter can become confused by the name of `examples/openai.py` when reading the `import openai` statement at the top of that same file. This will produce an error at runtime with a warning about a circular import.

**To Reproduce**
1. `python examples/openai.py`
2. See error

**Expected behavior**
Instead, the script should run through its routines.

**Screenshots**
```python
Traceback (most recent call last):
  File "/Users/tcpiplab/Tools/llm-guard/examples/openai.py", line 9, in <module>
    import openai
  File "/Users/tcpiplab/Tools/llm-guard/examples/openai.py", line 33, in <module>
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'openai' has no attribute 'ChatCompletion' (most likely due to a circular import)
```

**Additional context**
I solved this problem by:
1. Renaming `examples/openai.py' to 'examples/openai-test.py'
2. Adding `openai` to `requirements.txt`
3. Reinstalling the requirements with `pip install -r requirements.txt`

**Comment by asofter** [comment]
Hey @tcpiplab , thanks for raising this. I changed the name of this file.
