### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by NEWbie0709** [laiyer-ai/llm-guard#41]
Hi, I want to try LLM-Guard using Colab, and when I run the code, it shows an error:

WARNING:presidio-analyzer:model_to_presidio_entity_mapping is missing from configuration, using default
WARNING:presidio-analyzer:low_score_entity_names is missing from configuration, using default
WARNING:presidio-analyzer:Model en_spacy_pii_distilbert is not installed. Downloading...

✘ No compatible package found for 'en_spacy_pii_distilbert' (spaCy
v3.6.1)

An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

can I know how to fix it?

**Comment by asofter** [comment]
Hey @NEWbie0709 , thanks for reaching out. In our new version, we are removing this dependency but it still exists in v0.3.0. 

https://github.com/laiyer-ai/llm-guard/blob/v0.3.0/README.md#installation

Run

```sh
pip install https://huggingface.co/beki/en_spacy_pii_distilbert/resolve/main/en_spacy_pii_distilbert-any-py3-none-any.whl
```

**Comment by NEWbie0709** [comment]
Alright thankyou
