### ISSUE TITLE
Hi from the maintainer of the json-repair library

### ISSUE THREAD

**Issue by mangiucugna** [laiyer-ai/llm-guard#44]
Hi! I saw that you are using the library and that is great!

I was wondering why you decided to reimplement the repair_json method instead of calling the one provided, it's because the preprocessing done to the string breaks something? It's because of lazy loading?

Just wondering if there's something I can learn to improve the lib

Cheers

**Comment by mangiucugna** [comment]
I was expecting that json.load() to be the reason :)
Would be adding an option to skip the json.load() a good option for you? Something like 'skip_json_load=True'.

The reason why I decided against `orjson` is that I wanted to keep the library without external dependencies, especially orjson bring pyO3 that sometimes doesn't play well with some other libraries.

If you like the idea, I will release 0.4.0 (I recently released 0.3.0 to fix some reported issues with llama) and if you have suggestions please do let me know!

**Comment by asofter** [comment]
Sounds like a plan! I will make a change once you have the new version :) Thank you!

**Comment by mangiucugna** [comment]
here you go https://github.com/mangiucugna/json_repair/releases/tag/0.4.0

**Comment by mangiucugna** [comment]
FYI I was intrigued about the performance of the library so I did some profiling and found a way to make it 20% faster, small numbers for small JSON size but it's quite significant if you have large strings or doing large batch jobs.
So yeah, 0.4.1 is out

**Comment by asofter** [comment]
Awesome! Updated the library to use your exported function. Thank you!

**Comment by mangiucugna** [comment]
cheers!
