### ISSUE TITLE
Support for RAG

### ISSUE THREAD

**Issue by ghoshaishik505** [laiyer-ai/llm-guard#45]
Hi,
This is a cool library. Wondering, do you have support for RAG systems as well? If yes, where can I find som examples and docs?

**Comment by asofter** [comment]
Hey @ghoshaishik505 ,
Thanks for reaching out. I believe RAG can be supported by scanning before sending to the Vector DB but not yet on retrieval. We will check how to apply it during retriaval

**Comment by asofter** [comment]
Hey @ghoshaishik505  , we have an update on the RAG. Please check a new documentation page on how to secure RAG: https://llm-guard.com/usage/rag/#langchain.
