### ISSUE TITLE
Do you have  support for  Self-reflective  RAG  with LLM  Guard  ?

### ISSUE THREAD

**Issue by isheriff123** [laiyer-ai/llm-guard#48]
Do you have  support for  Self-reflective  RAG  with LLM  Guard either in the  input validation layer or in the  backend components ?
Do  you plan to derive any score of the  security threats and share it specifically based on the  "Type of  Security Threat " in different architectures  like  RAG and  Self- Reflective  RAG   ?

**Comment by asofter** [comment]
Hey @isheriff123 ,
Thanks for reaching out. 

Do you mean [Self-RAG](https://selfrag.github.io/)? No, we haven't tried LLM Guard with RAG on retrieval yet but I believe some scanners could be used before ingestion into a vector DB. We are planning to experiment with RAG and LLM Guard in December.

Indeed, scoring RAG would be important too, as it's also prone to attacks like prompt injection or data poisoning.

**Comment by isheriff123** [comment]
> Hey @isheriff123 , Thanks for reaching out.
> 
> Do you mean [Self-RAG](https://selfrag.github.io/)? No, we haven't tried LLM Guard with RAG on retrieval yet but I believe some scanners could be used before ingestion into a vector DB. We are planning to experiment with RAG and LLM Guard in December.
> 
> Indeed, scoring RAG would be important too, as it's also prone to attacks like prompt injection or data poisoning.

Yes, that's correct @asofter , any ETA for  exploring  RAG + llmGuard  for  Data Poisoning security threat attacks to derive some  Metrics for LLMGuard  if any plans are there  ?

**Comment by asofter** [comment]
Hey @isheriff123 , apologies for the delay. I am planning to finish it end of this month. We are working on something new which is related to llm-guard but a standalone product, and planning to release it in January.

**Comment by asofter** [comment]
In our [Slack](https://join.slack.com/t/laiyerai/shared_invite/zt-28jv3ci39-sVxXrLs3rQdaN3mIl9IT~w), you can engage in discussions, share your feedback and get latest updates.

**Comment by isheriff123** [comment]
> In our [Slack](https://join.slack.com/t/laiyerai/shared_invite/zt-28jv3ci39-sVxXrLs3rQdaN3mIl9IT~w), you can engage in discussions, share your feedback and get latest updates.

Fine, thanks @asofter

**Comment by asofter** [comment]
Hey @isheriff123 , we have an update on the RAG. It's unfortunately not self-reflective RAG but example of how llm-guard secures RAG with langchain: https://llm-guard.com/usage/rag/#langchain

**Comment by asofter** [comment]
Hey @isheriff123 , LlamaIndex has a support of Self-RAG: https://twitter.com/jerryjliu0/status/1754910093509066921

And we have a playbook on securing RAG with Llamaindex: https://llm-guard.com/usage/notebooks/llama_index_rag/

Hope it's helpful
