### ISSUE TITLE
[BanSubstrings] `substrings` should not default to None

### ISSUE THREAD

**Issue by baggiponte** [laiyer-ai/llm-guard#70]
I think the `substrings` argument in `BanSubstrigs` [defaulting to `None`](https://github.com/laiyer-ai/llm-guard/blob/3939533a3ef641eceb18ddff4bdbc9a03f49c898/llm_guard/input_scanners/ban_substrings.py#L41) is counter intuitive. I would suggest the following signature:

```python
def __init__(
        self,
        substrings: Sequence[str],
        *,
        match_type: Union[MatchType, str] = MatchType.STR,
        case_sensitive: bool = False,
        redact: bool = False,
        contains_all: bool = False,  # contains any
    ):
```

1. If it makes no difference to pass as argument a tuple of strings rather than a list, it's better to annotate `Sequence` over List. (`Sequence` is like `Iterable` but implements the `__len__` dunder method). 
2. It's much more intuitive to pass substrings as a default argument so you don't have to check whether it is None. In this way you don't have to maintain and test the [assertion](https://github.com/laiyer-ai/llm-guard/blob/3939533a3ef641eceb18ddff4bdbc9a03f49c898/llm_guard/input_scanners/ban_substrings.py#L62) that follows but you just rely on Python (and IDE tools!!!) to warn the user they didn't pass a required argument. It is generally recommended to avoid using assertions in production-grade code because if anyone runs `python -O` the optimisations remove the assert statements (though no one does it) (see #71).
4. (This is much more personal preference) I very much like using `*`. This forces the user to all the arguments after as keyword arguments. I think it'd be _very_ confusing to read `scanner = BanSubstrings(["a", "b", "c"], "str", False, True, False)`. In this case, the user would be forced to write `scanner = BanSubstrings(["a", "b", "c"], match_type="str", case_sensitive=False, redact=True, contains_all=False)`.

**Comment by asofter** [comment]
Hey @baggiponte , thanks for the ideas and detailed reasoning

1. I will experiment with this to see if it can make this for all the scanners.
2. Makes sense. It was initially using a JSON file results with default banned strings but it's not relevant anymore. 
3. Good idea. I made this change to make it easier to configure and then read the code.

**Comment by baggiponte** [comment]
Thank you for the quick response! One think only: adding `*` should be marked as breaking change because under a new version this line `scanner = BanSubstrings(["a", "b", "c"], "str", False, True, False)` would raise an error. It's not as bad because you are under v1 so minor changes (e.g. 0.34 -> 0.35) can still contain breaking API changes.

**Comment by asofter** [comment]
Yeah, I did it but probably will change a bit to make it more visible https://github.com/laiyer-ai/llm-guard/blob/main/docs/changelog.md

**Comment by asofter** [comment]
Sequence change was also done. Looks really good. Thank you!

**Comment by baggiponte** [comment]
Thank you for being so receptive! :) Mark the issue as closed whenever you feel more appropriate.

**Comment by asofter** [comment]
Thank you!
