### ISSUE TITLE
remove assertions in code

### ISSUE THREAD

**Issue by baggiponte** [laiyer-ai/llm-guard#71]
Hey there. This is a minor thing, but I noticed there are assertions are used in [some 9 files](https://github.com/search?q=repo:laiyer-ai/llm-guard+path:llm_guard+assert&type=code). This is not regarded as a best practice by many (e.g. see this [blog post](https://snyk.io/blog/the-dangers-of-assert-in-python/) from the code security service Snyk).

The TL;DR is: if you run `python -O` all assertions will be removed from the code. This will break the behaviour of llm-guard. No one does `python -O` but it's generally better if you can to avoid doing that. I could draft a PR if you wanted :)

EDIT. [here](https://github.com/laiyer-ai/llm-guard/blob/main/llm_guard/transformers_helpers.py#L105-L109C82) for example, you could write:

```python
from typing import Literal, get_args

ClassificationTask = Literal["text-classification", "zero-shot-classification", "ner"]

class LLMGuardInvalidClassifierTaskError(ValueError):
    pass

def pipeline(
    task: ClassificationTask, model: str, onnx_model: Optional[str] = None, use_onnx: bool = False, **kwargs
):
    if task not in get_args(ClassificationTask):
        raise LLMGuardInvalidClassifierTaskError
```

This provides several benefits:
1. Type annotations are self-documented code. The end user can always navigate to the definition of `ClassificationTask` and see the accepted values. There'd be slightly less problems if you forgot to update that in the docstring.
2. You would raise a custom exception that would make instantly clear that the error is raised from your library and because the user passed an invalid classifier task.

**Comment by asofter** [comment]
Hey @baggiponte , thank you for this idea. I removed all the asserts (found actually them in other libraries and thought it's a better idea but apparently not :) )

Now, changing the code to use Literal. I will also probably get rid of some enums

**Comment by baggiponte** [comment]
Great! Don't mind helping (even if it's just with reviewing the type annotation pr).

**Comment by asofter** [comment]
All assertions were removed. I tried to use Literal in a few places but enum there seems more relevant, so just used it in the transformers_helper as you suggested
